SELECT
	s.DCID,
	s.GRADE_LEVEL,
	ss.USERS_DCID,
	s.COURSE_NUMBER,
	s.SECTION_NUMBER,
	s.EXTERNAL_EXPRESSION,
	s.ROOM,
	s.SCHOOLID,
	t.DCID AS TERMSDCID,
	teachers.ID AS teacher
    
FROM SECTIONS s
    LEFT JOIN(
        SELECT
            st.SECTIONID,
            LISTAGG(u.LASTFIRST,', ') WITHIN GROUP (ORDER BY st.SECTIONID) "ID"
        FROM SECTIONTEACHER st
        INNER JOIN SECTIONS s ON s.ID = st.SECTIONID
        INNER JOIN TERMS t ON t.ID = s.TERMID AND t.SCHOOLID = s.SCHOOLID
        INNER JOIN SCHOOLSTAFF ss ON st.TEACHERID = ss.ID AND s.SCHOOLID = ss.SCHOOLID
        INNER JOIN USERS u ON ss.USERS_DCID = u.DCID
        WHERE t.YEARID = EXTRACT(YEAR FROM SYSDATE) + CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 8 THEN 1 ELSE 0 END - 1991
        GROUP BY st.SECTIONID
        ) TEACHERS ON TEACHERS.SECTIONID = s.ID
    INNER JOIN TERMS t ON t.ID = s.TERMID AND t.SCHOOLID = s.SCHOOLID
    INNER JOIN SCHOOLSTAFF ss ON s.TEACHER = ss.ID AND s.SCHOOLID = ss.SCHOOLID

WHERE t.YEARID = EXTRACT(YEAR FROM SYSDATE) + CASE WHEN EXTRACT(MONTH FROM SYSDATE) >= 8 THEN 1 ELSE 0 END - 1991
    AND s.id = 22375

ORDER BY s.DCID
